export const ActionTypes = {
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    DELETE_CARD:"DELETE_CARD",
    GET_SINGLE_PRODUCT : "GET_SINGLE_PRODUCT"
}