export const ActionTypes = {
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    DELETE_CARD:"DELETE_CARD",
    GET_SINGLE_PRODUCT : "GET_SINGLE_PRODUCT",
    FETCH_PRODUCTS_REQUEST:"FETCH_PRODUCTS_REQUEST",
    FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE:"FETCH_PRODUCTS_FAILURE",
    CHECKOUT_PRODUCTS_REQUEST:"CHECKOUT_PRODUCTS_REQUEST",
    CHECKOUT_PRODUCTS_SUCCESS:"CHECKOUT_PRODUCTS_SUCCESS",
    CHECKOUT_PRODUCTS_FAILURE:"CHECKOUT_PRODUCTS_FAILURE"
    
}